spring:
  profiles:
    active: dev

---

spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/MS
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
      pool-name: hikari-cp
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 10000
      connection-timeout: 10000
      validation-timeout: 10000
      max-lifetime: 580000
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: mysql

file:
  upload-dir: /Users/iujung/jaru_media